name: TuckedTee
favicon: null
layout_spectrum: 0.5171434099320322
typography_spectrum: 0.0577848341781646
title: Tucked Tee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#000000'
    - '#5a5a5a'
    - '#cacaca'
    - '#979797'
  brandStrength: 1
  lightness: 0.5329592176713049
  saturation: 0.012818564428016543
  rhythmicContrast: 0.8030369132757187
purpose: []
